import Head from 'next/head';
import { Feature } from 'ol';
import { useRef } from 'react';
import 'ol/ol.css';
import VectorLayer from 'ol/layer/Vector.js';
import VectorSource from 'ol/source/Vector.js';
import { Point } from 'ol/geom.js';
import { useRouter } from 'next/router.js';
import { useStop, useMap } from '@/common';

export default function BARTStop() {
    const router = useRouter()
    const { stop_id } = router.query
    const mapRef = useRef<HTMLDivElement>(null);
    const dataRef = useRef<HTMLDivElement>(null);
    const { data: stop_data } = useStop();
    const { data: map } = useMap(mapRef);

    if (stop_data && map && map.getAllLayers().length == 1) {
        const stop = stop_data["Contents"]["dataObjects"]["ScheduledStopPoint"].find((stop: any) => stop['id'] == stop_id);
        const coordinate = Object.values(stop!['Location']).map((x: any) => parseFloat(x as string));

        map.getView().setCenter(coordinate);
        map.addLayer(
            new VectorLayer({
                source: new VectorSource({
                    features: [
                        new Feature({
                            geometry: new Point(coordinate)
                        })
                    ]
                }),
                style: {
                  'circle-radius': 7,
                  'circle-fill-color': 'blue',
                },
            }),
        );

        dataRef.current!.innerHTML = stop['Name'];
    }

	return (
        <>
            <Head>
                <title>Train Catcher</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div ref={mapRef} style={{ height: "500px", width: "1000px"}}></div>
                <h1 ref={dataRef}></h1>
            </main>
        </>
    );
}
