import Head from 'next/head';
import { Link } from '@nextui-org/react';
export default function Home() {
	return (
		<>
			<Head>
				<title>Train Catcher</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Link href="/bart">BART</Link>
			</main>
		</>
	);
}
