import Head from 'next/head';
import { Feature } from 'ol';
import { useRef } from 'react';
import 'ol/ol.css';
import VectorLayer from 'ol/layer/Vector.js';
import VectorSource from 'ol/source/Vector.js';
import { Point } from 'ol/geom.js';
import { useRouter } from 'next/router.js';
import { useStop, useMap } from '@/common';

export default function BARTStop() {
    const router = useRouter()
    const { stop_id } = router.query
    const mapRef = useRef<HTMLDivElement>(null);
    const dataRef = useRef<HTMLDivElement>(null);
    const { data: stop_data } = useStop(stop_id as string);
    const map = useMap(mapRef);

    if (stop_data && map && map.getAllLayers().length == 1) {
        const name = stop_data.stops[0].stop_name;
        const coordinates = stop_data.stops[0].geometry.coordinates;
        map.getView().setCenter(coordinates);
        map.addLayer(
            new VectorLayer({
                source: new VectorSource({
                    features: [
                        new Feature({
                            geometry: new Point(coordinates)
                        })
                    ]
                }),
                style: {
                  'circle-radius': 7,
                  'circle-fill-color': 'blue',
                },
            }),
        );

        dataRef.current!.innerHTML = name;
    }

	return (
        <>
            <Head>
                <title>Train Catcher</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div ref={mapRef} style={{ height: "500px", width: "500px"}}></div>
                <h1 ref={dataRef}>loading stop...</h1>
            </main>
        </>
    );
}
